apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: kalilventura/api-conversao:v1
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: site-service
spec:
  selector:
    app: site
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort